language: python

matrix:
    include:
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6
        - os: linux
          python: nightly

        # Python runtime is not yet available on OS X
        # https://github.com/travis-ci/travis-ci/issues/2312
        - os: osx
          language: generic
          env: PYTHON_VERSION=3.4.6
        - os: osx
          language: generic
          env: PYTHON_VERSION=3.5.3
        - os: osx
          language: generic
          env: PYTHON_VERSION=3.6.0

    allow_failures:
        - python: "nightly"
        - os: osx
          language: generic
          env: PYTHON_VERSION=3.4.6

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sh ci/install_python_for_osx.sh; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source ~/venv/bin/activate; fi

install:
    - "pip install -U pip"
    - "pip install -U pytest coveralls"
    - "pip install ."
    - "pip freeze"

script:
    - python setup.py test

after_success:
    - coveralls

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/7498c1d7f0e50c212e1a

deploy:
    provider: pypi
    user: M157q
    password:
        secure: fTh18TIYqUsyGEg4vIEmxcxYPFCW5VDp4Ma+kuUjDh6qBpcY4akS6M16iOEGJp2QLndJiFdjW2JSOY7TR+HUCBEm6VTU7uYITPlNtYbMSKo0QjTkuLM/6/rufFwUMiDaw/mGSUuW04T6/+2RGFXFU9/JrRJqa96Le3Q9FqnVaQg=
    on:
        branch: master
        tags: true
        distributions: sdist bdist_wheel
        repo: zdict/zdict
